### ISSUE TITLE
Speed upvoting

### ISSUE THREAD

**Issue by SuggeElson** [MattyIce/postpromoter#16]
May we need to add a way to bot upvote in every 5 sec ( instead 30 ) and after upvotes are done, to start broadcasting the comments. 

This may will be better for big bots like @upme where each round comes with - 60+ bids and upvoting round last around 30 minutes some time. 

Separate the voting and commenting will speed up the bot and no rounds will be lost. Right now bot has around 9 rounds in the day.

**Comment by MattyIce** [comment]
This has been implemented, thanks for the suggestion!
