### ISSUE TITLE
Process get killed after few hours

### ISSUE THREAD

**Issue by zakariachowdhury** [MattyIce/postpromoter#18]
I am hosting the app into DigitalOcean with Ubuntu. I am having hard time to keep it alive. I tried both nohup & forever commands. But still it gets killed. Can you please help me to figure this out or suggest any other servers?

**Comment by SuggeElson** [comment]
Try pm2 to manage node process

**Comment by zakariachowdhury** [comment]
pm2 solves the issue, thank you very much.
