### ISSUE TITLE
Wait for vote to complete before scheduling next one

### ISSUE THREAD

**Issue by MattyIce** [MattyIce/postpromoter#19]
Currently the bot schedules the next vote immediately after sending the previous vote, however sometimes it takes a few seconds for a vote to go through meaning that the next vote will come too soon (within 3 seconds) and get an error.

Instead the bot should schedule the next vote after receiving the response from the previous vote.

**Comment by emre** [comment]
3 seconds still may cause some throttling errors from the chain. (Even you wait the response) I updated my bots to wait 4 seconds and the problem solved.

**Comment by SuggeElson** [comment]
I use 5 and works fine, also Matt change it to 10 by default in the new version.

**Comment by MattyIce** [comment]
The code is now updated to wait until the previous vote completes before sending the next one, and waits 5 seconds just to be on the safe side.
