### ISSUE TITLE
bot over-voting

### ISSUE THREAD

**Issue by bitcoiners** [MattyIce/postpromoter#21]
Currently bot votes more that 100%, turning rounds into 3+ hours long. Can something be done about this?
![image](https://user-images.githubusercontent.com/38520/34657925-7bf54ae0-f45d-11e7-950e-12038763f5ee.png)

**Comment by SuggeElson** [comment]
This is the STEEMIT core bug with vote rounds is almost impossible to do something.

**Comment by bitcoiners** [comment]
Which bug? Was it reported to steem?

**Comment by bitcoiners** [comment]
Which bug? Was it reported to steem?

**Comment by bitcoiners** [comment]
It seems over-voting is different for different bots. 1 round - 2 hours 34 minutes.
![image](https://user-images.githubusercontent.com/38520/34659086-75854e1c-f467-11e7-8d09-4110723807ae.png)
pushup (uses same postpromoter) 1 round - 3 hours and 5 minutes
![image](https://user-images.githubusercontent.com/38520/34659085-7583afbc-f467-11e7-82d1-34168a8af0c9.png)

**Comment by bitcoiners** [comment]
Seems rounds keep getting longer. Now it is over 4.5 hours.
![image](https://user-images.githubusercontent.com/38520/34669412-1f4182b8-f4a4-11e7-9098-fae0fb9fc100.png)

**Comment by SuggeElson** [comment]
Read the post of @therealwolf 
I advise you to increase the min bid to at least 0.5 because now every 0.1 you got the bot give around 0.83 upvote and this is causing the overvoting

**Comment by bitcoiners** [comment]
Got it. Thanks. Changed min bid to 1. That should help.

**Comment by SuggeElson** [comment]
Sure here is it - https://steemit.com/minnowbooster/@minnowbooster/minnowbooster-wrong-vote-values-the-problem-and-the-upcoming-solution

**Comment by bitcoiners** [comment]
After raising min bid rounds got back down to about 2 h, 27 minutes. Over-votes a little, but not critical.
