### ISSUE TITLE
delegator rewards

### ISSUE THREAD

**Issue by bitcoiners** [MattyIce/postpromoter#23]
### Summary
In order to attract delegated Steem Power bot operators can offer delegator rewards.
Delegators can be paid a percentage of revenue generated by delegated SP or a fixed rate.
Rewards can depend on size of delegation.
Bot operators can offer delegators one or both reward types and choice of reward asset. 
Blacklisted delegators don't get delegator rewards.

_Examples_:
- 80% of revenue generated by delegated SP paid out as SBD or STEEM.
- 1   STEEM per 1000 SP paid daily for delegations less than 10,000 SP. 
  1.1 STEEM per 1000 SP paid daily for delegations between 10,000 and 100,000 SP.
  1.2 STEEM per 1000 SP paid daily for delegations larger than 500,000 SP   
- @blocktrades does not get delegator rewards.
 

#### Implementation proposal

_Sample configuration settings_
```
"delegator_rewards": {
    "active": true,
    "frequency": "daily",
    "execute_time": 18,
    "memo": "#Delegator Rewards - {balance}",    
    "type": "both", // set supported reward types, options are "fixed", "variable" or "both"
    "default": "fixed" //  set default reward type if "both" types are supported
    "asset": "STEEM", // or "SBD" (default rewards asset)
    "blacklist":[ // does not get delegator rewards
      "blocktrades"
    ], 
    "rates":[
      {
	"upto": 10000, // less than 10,000 delegated SP.
      	"fixed": {
          "reward": 1, // 1 for each 1000 delegated SP per day
          "delegation": 1000 
          "period": "day", // "day", "week", "month", "year"                   
        },
      	"varible": 80, // % of revenue generated by delegated SP
      },
      {
	"upto": 100000,
      	"fixed": {
          "reward": 1.1,
          "delegation": 1000 // reward for each 1000 
          "period": "day", // "day", "week", "month", "year"                   
        },
      	"varible": 81, // % of revenue generated by delegated SP
      },
      {
	"over": 100000,
      	"fixed": {
          "reward": 1.2,
          "delegation": 1000 
          "period": "day",                    
        },
      	"varible": 82, // % of revenue generated by delegated SP
      }
    ]
}
```
If both fixed and variable reward types are supported, delegators can switch between them by sending bot a transfer with memo "fixed" or "variable".
Delegator can select what asset to get paid in by sending bot a transfer with memo "sbd", or "steem". 

---
**Please comment and suggest improvements.**

**Comment by MattyIce** [comment]
You can already do this by setting a second withdrawal account for the fee like this:

```
"accounts": [
      {
        "name": "$delegators",
        "stake": 9000
      },
      {
        "name": "your_account",
        "stake": 1000
      }
```

In the configuration above 90% of earnings are paid out to delegators and 10% is paid out to "your_account" as the fee. Let me know if I'm misunderstanding the issue.

**Comment by bitcoiners** [comment]
Not all delegators should get auto-pay. For example SP delegated by blocktrades should not get payouts.

**Comment by MattyIce** [comment]
Ah got it, that's a good point. I will work on that as soon as I have time, thanks for bringing it up!

**Comment by bitcoiners** [comment]
Another alternative is to auto-pay fixed amounts to delegators, for example a 25% apr on delegated SP.

**Comment by themarkymark-steem** [comment]
+1

**Comment by bitcoiners** [comment]
Some more notes on delegator rewards. 
It could have configurable options like payment type (fixed rate or percentage of revenue).
Fixed rate option could be set as APR, or certain amount paid each period (day, week, month..) for delegated SP . 
Also rate can depend on size of delegation and delegation length in days.

**Comment by bitcoiners** [comment]
How about as an experiment this issue is tackled as a paid bounty?
I am willing to put 50 Steem toward it's completion.

**Comment by bitcoiners** [comment]
Ok. I will prepare the spec and publish here.

**Comment by bitcoiners** [comment]
I updated intro post for this issue with a draft spec for delegator rewards. Please comment and suggest improvements.

**Comment by bitcoiners** [comment]
Who wants to take this issue on? Who wants to see it done? Who wants to contribute funds?
Let me know!

**Comment by MattyIce** [comment]
Thanks for the detailed writeup @bitcoiners! I'm still not clear about how the actual distributions would get calculated on a daily basis though, for example if we have the following delegators:

1. user_a - 5,000 SP delegated, variable rate, paid in SBD
2. user_b - 50,000 SP delegated, fixed rate, paid in STEEM
3. user_c - 500,000 SP delegated variable rate, no payout asset selected

Then if the bot ends the day with 1,000 SBD and 500 STEEM, how do you calculate the payouts for each delegator based on your example configuration?

**Comment by bitcoiners** [comment]
Here is how I see it. 
sbd_price = $7
steem_price = $6
revenue = 1000 * 7 + 500 * 6 = $10000
delegated_sp = 5000 + 50000 + 500000 = 555000
user_a_share_of_delegated_sp = 5000 / 555000 = 0.009009009
user_c_share_of_delegated_sp = 500000 / 5550000 = 0.900900901

user_a_rewards_$ = 0.8 * 10000 * 0.009009009 = $72.07 ( 10.296 sbd)
user_b_rewards_$ = 1.1 * 50000 / 1000 = 55 steem * 6 = $330
user_c_rewards_$ = 0.82 * 10000 * 0.900900901 = $7387.38 (1231.231 steem)

**Comment by bitcoiners** [comment]
Spec has grown since I started this issue, so count me in for 100 Steem to have this bounty completed.

**Comment by bitcoiners** [comment]
Maybe it makes sense to develop this issue as a stand alone bot, so that it can be used by postpromoter and drotto bot operators, as well as others.

**Comment by MattyIce** [comment]
Yea I think that is a good idea - I think this is a bit too complicated as you have it specified. I'm guessing this fits your needs but what exists today seems to fit the needs of most bot owners I am working with. I am open to making some changes to add new functionality here and there but this is really a lot.
