### ISSUE TITLE
d.tube posts bids rejected

### ISSUE THREAD

**Issue by bitcoiners** [MattyIce/postpromoter#26]
This bid was rejected by the bot.
https://d.tube/#!/v/cloudbuster/u3w1h0b7

**Comment by MattyIce** [comment]
d.tube uses a different URL format than other sites. For now d.tube bids will need to be submitted using the standard URL format: https://steemit.com/hearthstone/@cloudbuster/u3w1h0b7

If you would like to submit a pull request to handle d.tube links I will be happy to review and merge it.

**Comment by MattyIce** [comment]
This is resolved thanks to the PR submitted by @big-boi - thank you!
