### ISSUE TITLE
auto change the rpc server

### ISSUE THREAD

**Issue by SuggeElson** [MattyIce/postpromoter#28]
It is possible to add auto change function for RPC servers.
IN config will have 4-5 and if one fails bot will hope to other without mess the rounds.

**Comment by themarkymark-steem** [comment]
This is a big one for me too, I believe this is being worked on with high priority now.

**Comment by MattyIce** [comment]
Hey @themarkymark-steem, @SuggeElson - I have just implemented this feature. I have tested it a bunch locally and used my hosts file to simulate a node going down and it all seems to be good, but it has not been tested in a live production environment yet so use it at your own risk at this point.

I will be testing it out on some of my smaller bots over the next week and then push to the larger bots later if all goes well.

**Comment by SuggeElson** [comment]
Great, i will implement it for next round so any bugs should find fast.
