### ISSUE TITLE
app agent

### ISSUE THREAD

**Issue by inertia186** [MattyIce/postpromoter#3]
Be sure to add your `{"app": "agent/version"}` element in the `json_metadata` field of the reply comment when your bot votes. :D

**Comment by MattyIce** [comment]
Thanks! Great to hear from the original drotto creator! I have added this in this commit: https://github.com/MattyIce/postpromoter/commit/aaaf1fd11d7fc16fd48673b5d1c3031bc785a2bd

Please let me know if you have any other feedback!
