### ISSUE TITLE
Blacklist updates

### ISSUE THREAD

**Issue by MattyIce** [MattyIce/postpromoter#32]
I would like to make the following updates to the blacklist feature:

1. Add a config setting for the blacklist file location which can also include a URL
2. Add a config setting for whether or not blacklisted users should receive a refund for their bids
3. Add an option to respond to blacklisted users with a 0.001 SBD transaction letting them know they are blacklisted (with a configurable memo)
4. Add an option to automatically transfer any bids sent from blacklisted users to an external account to help fight spam (e.g. steemcleaners, cheetah, etc)

**Comment by SuggeElson** [comment]
Great i love it.

**Comment by themarkymark-steem** [comment]
https://github.com/MattyIce/postpromoter/issues/36

**Comment by MattyIce** [comment]
All of the features listed here should now be done, and hopefully most of the bugs fixed as well!
