### ISSUE TITLE
Flag Signals

### ISSUE THREAD

**Issue by themarkymark-steem** [MattyIce/postpromoter#33]
I would really like to see an option to put accounts that act as flag signals.

For example, if cheetah flags a post, it should be considered blacklisted.  Being able to add additional ones like spaminator, mack-bot, blacklist-a, and our own signals would be nice.

Ideally, I was thinking a check would be made the moment the bid is received, and once prior to voting.

**Comment by MattyIce** [comment]
This has been added with the latest commit.
