### ISSUE TITLE
Bid API Failover

### ISSUE THREAD

**Issue by themarkymark-steem** [MattyIce/postpromoter#34]
I'd like to see the bid api failover to the old method if the api is unable to be accessed.  Or some method to handle connectivity issues with the API rather than have the bot just disappear from the site.

**Comment by MattyIce** [comment]
@themarkymark-steem this is really an issue for the https://github.com/MattyIce/bottracker project and i believe the site should handle this situation better now than when you originally submitted the issue. But feel free to re-post there if you feel it still needs to be addressed.
