### ISSUE TITLE
co-sponsored bot developer

### ISSUE THREAD

**Issue by bitcoiners** [MattyIce/postpromoter#35]
@MattyIce Thank you for creating this great bot. 
I would like to suggest that users of the  bot co-sponsor a developer to improve the code and add many useful features.
If all of us contribute, we can fund a part time or even a full time developer to make postpromoter bot the best it can be. 
Let me know if you agree and willing to contribute funds.

**Comment by RomanAround** [comment]
I agree. I will contribute defiantly. Count me in. Create a mechanism etc. 

RomanAround 

@romanaround steemit

**Comment by MattyIce** [comment]
This is an interesting idea! @bitcoiners what features / changes would you have them work on? There's not really that many things listed as issues so a full or even part time developer could probably knock them out pretty quickly.

**Comment by bitcoiners** [comment]
There are quite a few things that can be done and I am sure not the only one with a wish list.
Here is my short list.
1. Tests, tests and more tests (we need test driven development to ensure fail free operation and evolution of the bot).
2. Improve error handling, there should never be a lost vote, refund or comment. 
3. Delegator rewards withdrawals https://github.com/MattyIce/postpromoter/issues/23 with configurable options like payment rate, APR or coin per delegated SP per period. 
4. Reporting, Usage statistics
5. Stealth votes option 
https://github.com/MattyIce/postpromoter/issues/20
6. Option to auto-sell alternative currency bids
https://github.com/MattyIce/postpromoter/issues/20
7. Add support for alternative url formats (dtube, dmania, and others)

**Comment by bitcoiners** [comment]
We will need to consider how it will be organized. One option is to use a bounty like system. Proposals are welcome.

**Comment by MattyIce** [comment]
I'm going to close this - I always welcome the help with development and love the idea of bounties, but I don't think it should be an "issue" on the GitHub project.
