### ISSUE TITLE
Config Setting: min_refund

### ISSUE THREAD

**Issue by themarkymark-steem** [MattyIce/postpromoter#44]
I would like to see a setting min_refund that controls how high a transfer has to be to be eligible for a refund.  My plan is to set it to 0.001 to prevent wallet memos going back and forth and raise it if someone attempts to use it maliciously (sets it to 0.002 to ping pong).

The scenarios I am trying to avoid:

1) wallet spam getting refunded
2) wallet memos coming in and being refunded back (typical you didn't vote my post 5 minutes after their bid)
3) ping pong attack (malicious, or just between two bots)

**Comment by MattyIce** [comment]
Just added this. Good idea and was a pretty simple change.

**Comment by themarkymark-steem** [comment]
This doesn't seem to factor in Steem transfers.

**Comment by MattyIce** [comment]
I didn't test with a bot that only accepts SBD. Should be fixed with the latest commit: https://github.com/MattyIce/postpromoter/commit/65ef0ecdb58b41c924411334d411af76ef048999
