### ISSUE TITLE
Add ability to limit bids per author per round

### ISSUE THREAD

**Issue by MattyIce** [MattyIce/postpromoter#45]
In certain cases rather than blacklisting accounts I think it would be better to limit it to one bid per author per bidding round.

**Comment by themarkymark-steem** [comment]
I'm ok with authors bidding on multiple posts per round, especially if it is different authors.  My concern is more focused on their general activity, posting 10+ times a day to maximize rewards on stolen or copypasta content.  That said, I'm not opposed to the feature at all, good to have options, never know where life may take us.

**Comment by MattyIce** [comment]
> especially if it is different authors
This is looking at the author of the post, not the sender of the bid. So the idea is to limit one author getting votes on a bunch of their posts in the same round. It should also help limit people being able to buy votes on 10+ posts / day somewhat.

**Comment by themarkymark-steem** [comment]
The problem is there are 50+ bots and 40,000 users publishing low effort content.
I like the option though, I would even go so far to add an option max_vote_day and max_vote_round.

**Comment by MattyIce** [comment]
I would like to add an option for max by day also, but that's going to be a more involved change since the software doesn't currently keep track of anything past the previous round.

**Comment by MattyIce** [comment]
This is done in this commit: https://github.com/MattyIce/postpromoter/commit/65ef0ecdb58b41c924411334d411af76ef048999
