### ISSUE TITLE
Reject bids before x minutes

### ISSUE THREAD

**Issue by themarkymark-steem** [MattyIce/postpromoter#47]
I've noticed a huge increase in the number of bids coming in for posts created immediately before the end of a bidding window to abuse curation rewards.  The users doing this are typically using spammy posts.  In HF20 the first 15 minutes will go back to the reward pool and will be another factor to deal with.

I propose having a setting to reject bids before x minutes.  I say we have a min age as well.

**Comment by MattyIce** [comment]
Just added "min_post_age" setting in latest commit here: https://github.com/MattyIce/postpromoter/commit/fadf17a109e2ef9223decf27a8fe3bd2245677a3

**Comment by themarkymark-steem** [comment]
This doesn't seem to be working.

I get this whenever someone submits an early bid:

![sharex_2018-02-20_03-15-20](https://user-images.githubusercontent.com/33408375/36413410-48766c16-15ec-11e8-8efe-da8369bdb578.png)

**Comment by MattyIce** [comment]
@themarkymark-steem Please make sure you added the transfer memo for min post age refund to config.json:

```
"min_age": "Refund for invalid bid: {amount} - Posts cannot be less than {min_age} minutes old.",
```
