### ISSUE TITLE
Add option to accept STEEM bids

### ISSUE THREAD

**Issue by MattyIce** [MattyIce/postpromoter#5]
Currently the bot only accepts bids in SBD, but with all of the SBD pumps happening recently there should be an option to also accept bids in STEEM.

**Comment by SuggeElson** [comment]
Not bad idea, also i see booster accept steem so we need to add a new icon to indicate this on the page.

**Comment by MattyIce** [comment]
Added with last commit. Also bot tracker site has been updated to indicate this.
