### ISSUE TITLE
Don't pay out new delegations that come in right before payout time

### ISSUE THREAD

**Issue by MattyIce** [MattyIce/postpromoter#50]
If a new delegation comes in right before the scheduled daily payout time, it takes earnings from the other delegators even though it didn't contribute to the bot's earnings for that full day. New delegations should have to wait until the next withdrawal to receive their payout.

**Comment by themarkymark-steem** [comment]
I think having them wait for the first full cycle makes the most sense.   That's how randowhale handles it, 

Each account that delegates will be included starting in the round following the current round.
Any increase in delegation will take affect in the following round.
Any reduction in delegation will take affect in the current round.

**Comment by MattyIce** [comment]
Done in commit: https://github.com/MattyIce/postpromoter/commit/f5999aa492d8893bb4846f11d9e580ead82d76b1
