### ISSUE TITLE
Double vote for the same URL overcomes the max bid value

### ISSUE THREAD

**Issue by brupvoter** [MattyIce/postpromoter#52]
I set up a maximum limit for bid value at 0.8 SBD.  But one have sent two bids with 0.8 sbd, each one, for the same Post URL. So, the bot accepted both bids and the bottracker site, at "bidding round details", shows a bid of 1.6 sbd for this unique Post URL.

If I set up the  {"max_per_author_per_round": 1} It should avoid this situation.  But I think that fixing this bug would be better for those who did not set up this feature or set it up to "2" for instance.

Thank you, in advance.

**Comment by MattyIce** [comment]
Good catch @brupvoter! This should be fixed with this commit: https://github.com/MattyIce/postpromoter/commit/29dcbd70e046ac0f77de5c94a6e976bbee8f8cd9
