### ISSUE TITLE
Adjustment to how min_age works

### ISSUE THREAD

**Issue by themarkymark-steem** [MattyIce/postpromoter#53]
Right now min_age acts as an instant reject or allow parameter.  While this solves the problem after more thought I think a better solution is in order.

First I believe the time until next vote should be factored in, if the post will not be voted before the min_age then it should be allowed even if it is a brand new post.

Second, if it does not meet the min_age requirement, I believe it should be pushed into the next bid window, rather than being rejected.  The main reason for this is it is very frustrating to sit for 15-20 minutes until you are "allowed" to submit a bid.  It's not a good user experience and it's bad for bot owners to reject otherwise valid bids.

Booster has a feature in their software if a bid takes up x amount of a bid window, all other bids are shifted to the next window.  This functionality can be re-used to solve this problem and potentially (yes please) add that functionality (will open a separate issue).

Thanks, I love all the updates!

**Comment by MattyIce** [comment]
I updated it to include the time until the next vote in the min_post_age calculation. I didn't have time to do the pushing into next round part yet since that's more work but I will get to it. In the meantime it will still send a refund.

**Comment by MattyIce** [comment]
This was completed in commit: https://github.com/MattyIce/postpromoter/commit/ffd7d45313ef9f1a45aeb0df32e2087839ca7314
