### ISSUE TITLE
Push bidders to new window

### ISSUE THREAD

**Issue by themarkymark-steem** [MattyIce/postpromoter#54]
This functionality can piggyback off some of the code for issue [53](https://github.com/MattyIce/postpromoter/issues/53).

The idea if one bidder puts in a large enough bid that takes up X % of a window, all other bids are moved to the next window and that bidder gets 100% of the window.  Booster implements this functionality so if one bidder submits a bid that would eat up over 75% of the bid window, it uses the entire window and the rest of the bids are shifted for the next window instead.  

This prevents large bids dominating a window and dwarfing everything else.

**Comment by MattyIce** [comment]
@themarkymark-steem there is already the round_fill_limit setting to limit how full the round can get. Currently it just refunds any bids that come in that would push it over the limit, but if it instead just pushed those bids to the next round that seems like it would solve this use case (potentially in a better way than booster). What do you think?

**Comment by themarkymark-steem** [comment]
Agreed.

**Comment by MattyIce** [comment]
This was done in commit: https://github.com/MattyIce/postpromoter/commit/ffd7d45313ef9f1a45aeb0df32e2087839ca7314
