### ISSUE TITLE
Update Vote weights of Last Round section from API urls of bot owners (if given)

### ISSUE THREAD

**Issue by outlier89** [MattyIce/postpromoter#60]
Currently, the vote weights of the current and the last rounds are calculated by the steembottracker site itself. Bidders check the last round tab to confirm their vote weight and even if there is a slight difference, their confidence in the bot is undermined. So it would be better if the vote weights are directly updated from the bid apis of the bot owners.

**Comment by MattyIce** [comment]
@outlier89 yes this is a good change, but it is really an issue for the bottracker project and not the post promoter software. Also I believe this change has recently been submitted as a pull request to that project which I will review and merge shortly.

**Comment by outlier89** [comment]
Great. Sorry for posting it here instead of bottracker and thanks for your response.
