### ISSUE TITLE
Delegator vested_shares in file set to 0.  (CAREFUL when updating from 1.8.9 to 1.9.0)

### ISSUE THREAD

**Issue by eonwarped** [MattyIce/postpromoter#63]
The symptom: delegators.json  has many delegator's vesting_shares set to 0. 
This caused the last day's auto withdrawal payout to be off.

Looking at logs, I see the following delegator changes and events:

Delegations before Saturday payout got set to 0 for Monday.
...
Saturday withdrawal (Looks normal)
....
A few delegations here that were still included in Monday's payout
...
(Sunday restart, upgraded to version 1.9.0 from 1.8.9.. Aha! **This is why**)
Delegators Loaded (from disk) - 33 delegators and 8866039.696985 VESTS in total!
...
*** Delegation Update - ZZZ has delegated 2041884.998212 VESTS
...
Sunday Withdrawal. Looks correct.
...
*** Delegation Update - YYYY has delegated 153140.607630 VESTS
*** Delegation Update - YYYY has delegated 255228.880482 VESTS
*** Delegation Update - XXXXX has delegated 204178.726455 VESTS
*** Delegation Update - XXXXX has delegated 40835.739609 VESTS
*** Delegation Update - XXXXX has delegated 0.000000 VESTS
*** Delegation Update - XXXXX has delegated 10208.917816 VESTS
...
Monday Withdrawal. (Wrong distribution)
...
(Restart after investigating. Failed to clear json file)
Delegators Loaded (from disk) - 35 delegators and 3615535.426986 VESTS in total!
...
(Restart, clearing json file)
Delegators Loaded (from account history) - 35 delegators and 12095612.302691001 VESTS in total!
...

**Comment by eonwarped** [comment]
Sorry for the weirdness, this was me figuring out why I got my bug. Perhaps should be a warning somewhere, but not sure where about the update. Actually this may bite someone else that updates the software as well.

**Comment by eonwarped** [comment]
Having people re-initialize the delegators.json file suffices (delete it when restarting)

**Comment by MattyIce** [comment]
Thanks for reporting this @eonwarped and sorry it took so long for me to get to it. I just pushed some code to add an upgrade process between versions, so now if anyone else updates to 1.9+ from an older version it will rename the delegators.json file automatically so it gets reloaded from the account history and avoids this issue.

Commit: https://github.com/MattyIce/postpromoter/commit/13bf4cec087b304287b160bf2e3d5baf215a1ea1
