### ISSUE TITLE
blacklist for delegators auto_withdrawal

### ISSUE THREAD

**Issue by bitcoiners** [MattyIce/postpromoter#66]
Not all delegators should be getting rewards, (ex blocktrades) and should be on blacklist for delegator rewards. 
A setting like this is needed.
```
  "blacklisted_delegators": ["blocktrades"],
```

**Comment by MattyIce** [comment]
This is already possible using the "overrides" option in the auto_withdrawal account object. If you don't want blocktrades to get a delegator payout you set:
```
"accounts": [
      {
        "name": "$delegators", 
        "stake": 8000,
        "overrides": [  
          { "name": "blocktrades", "beneficiary": "beneficiary_account" }
        ]
      },
```
