### ISSUE TITLE
I have an issue where I comme back to my server and process has failed

### ISSUE THREAD

**Issue by JordanFAVRE** [MattyIce/postpromoter#69]
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'url' of undefined
    at outstanding_bids.find.bid (/home/xx/xx/postpromoter/postpromoter.js:519:75)
    at Array.find (native)
    at /home/xx/xx/postpromoter/postpromoter.js:519:45
    at /home/xx/xx/postpromoter/node_modules/steem/lib/api/transports/http.js:94:9
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by MattyIce** [comment]
@JordanFAVRE I think this issue should be fixed in the latest version.
