### ISSUE TITLE
 Error loading bot account: RPCError: Unable to acquire database lock

### ISSUE THREAD

**Issue by bitcoiners** [MattyIce/postpromoter#74]
Bots have been acting up today.
```
...
Thu Apr 19 2018 03:19:48 GMT-0700 (PDT) - First run - loading all transactions since bot was stopped.
Thu Apr 19 2018 03:20:19 GMT-0700 (PDT) - Error Count: 1, Current node: https://api.steemit.com
Thu Apr 19 2018 03:20:19 GMT-0700 (PDT) - Error loading bot account: RPCError: Unable to acquire database lock

```
And bot tracker is showing that none of the bots are voting. 
![image](https://user-images.githubusercontent.com/38520/38986359-6b69b09c-43f6-11e8-85c1-1ec3e4d12e66.png)

**Comment by themarkymark-steem** [comment]
Main api.steemit.com is down. Currently, steemit.com is 12 days out of sync.

**Comment by bitcoiners** [comment]
Options?

**Comment by themarkymark-steem** [comment]
Not much until Matt can switch the site to a different node.  But the bots will work if they are not using api.steemit.com but I think most are.
