### ISSUE TITLE
Error loading account history: Error: Invalid response id: undefined

### ISSUE THREAD

**Issue by bitcoiners** [MattyIce/postpromoter#75]
Bot problems today..
```
Mon Apr 23 2018 10:20:53 GMT-0700 (PDT) - Error Count: 6, Current node: https://api.steemit.com
Mon Apr 23 2018 10:20:53 GMT-0700 (PDT) - Error loading account history: Error: Invalid response id: undefined
Mon Apr 23 2018 10:21:02 GMT-0700 (PDT) - Error Count: 1, Current node: https://api.steemit.com
Mon Apr 23 2018 10:21:02 GMT-0700 (PDT) - Error loading account history: Error: Invalid response id: undefined
Mon Apr 23 2018 10:21:12 GMT-0700 (PDT) - Error Count: 2, Current node: https://api.steemit.com
Mon Apr 23 2018 10:21:12 GMT-0700 (PDT) - Error loading account history: Error: Invalid response id: undefined
```

**Comment by MattyIce** [comment]
Yes, the SteemIt API node is having issues with account history today. I suggest using rpc.buildteam.io instead.

**Comment by bitcoiners** [comment]
my config file has

"rpc_nodes": [
    "https://api.steemit.com",
    "https://rpc.buildteam.io",
    "https://steemd.minnowsupportproject.org",
    "https://steemd.privex.io",
    "https://gtg.steem.house:8090"
  ],

Is the bot not supposed to switch to another  node automatically, if it has connection problems?

**Comment by MattyIce** [comment]
Yea, the problem is that api.steemit.com isn't currently failing often enough to trigger it, and it also seems to be a few hours behind on account history which isn't even an error that the code can catch. Unfortunately this still requires manual intervention right now.
