### ISSUE TITLE
Roll bid overflow to next rounds

### ISSUE THREAD

**Issue by macans7** [MattyIce/postpromoter#79]
Given the bot is configured to give a positive ROI to bidder
And there are more votes than the bot can give positive ROI in the next round
When the bot votes in the next round
Then all rolled over vote entries are voted on

Instead the bot should continue to take only the next X number of vote entries that will guarantee positive ROI and roll remaining to a second (or third, fourth, etc.) time.

This issue typically occurs with smaller valued bots, especially after the bot was down for some time.

**Comment by MattyIce** [comment]
This should be fixed in the latest version. Bids that overflow the next round will be refunded in full.
