### ISSUE TITLE
Microsoft Jscript compilation error

### ISSUE THREAD

**Issue by KalyaniForensic** [MattyIce/postpromoter#88]
When I try to run the postpromoter.js file i am getting error at line 2 char 1
![image](https://user-images.githubusercontent.com/19181120/43369078-21e0ffb4-9385-11e8-8004-beec44a137b2.png)

**Comment by MattyIce** [comment]
Hi @KalyaniForensic I'm not sure how you are trying to run this, but you need to install nodejs and run it that way. It looks like you may just be trying to double click on the file which will not work.
